/**
 * Auto-generated from data/channels.tsv — do not edit by hand.
 * Regenerate: npm run gen:channels
 */

export const GENERATED_DEFAULT_CHANNEL_GROUPS = [
  {
    id: "saramin",
    label: "사람인",
    faviconDomain: "saramin.co.kr",
    children: [
      { id: "ad-053", label: "플래티넘 플러스 (PC + M)", utm_source: "saramin", utm_medium: "platinumplus" },
      { id: "ad-054", label: "프라임 플러스 (PC + M)", utm_source: "saramin", utm_medium: "primeplus" },
      { id: "ad-055", label: "스페셜 플러스 (PC + M)", utm_source: "saramin", utm_medium: "specialplus" },
      { id: "ad-056", label: "핫픽 M", utm_source: "saramin", utm_medium: "hotpickm" },
    ],
  },
  {
    id: "jobkorea",
    label: "잡코리아",
    faviconDomain: "www.jobkorea.co.kr",
    children: [
      { id: "ad-057", label: "메인 빅 배너", utm_source: "jobkorea", utm_medium: "mainbig" },
      { id: "ad-058", label: "메인 우측", utm_source: "jobkorea", utm_medium: "mainright" },
      { id: "ad-059", label: "프리미어 채용관 (PC+M)", utm_source: "jobkorea", utm_medium: "premier" },
      { id: "ad-060", label: "First VVIP 채용관 (PC + M)", utm_source: "jobkorea", utm_medium: "firstvvip" },
    ],
  },
  {
    id: "catch",
    label: "캐치",
    faviconDomain: "catch.co.kr",
    children: [
      { id: "ad-061", label: "AI 매칭 배너", utm_source: "catch", utm_medium: "ai" },
      { id: "ad-062", label: "메인 대형 배너", utm_source: "catch", utm_medium: "mainbig" },
      { id: "ad-063", label: "지금 주목받는 공고", utm_source: "catch", utm_medium: "pop" },
      { id: "ad-064", label: "카테고리 공고", utm_source: "catch", utm_medium: "category" },
      { id: "ad-065", label: "캐치 추천 공고", utm_source: "catch", utm_medium: "recommend" },
      { id: "ad-066", label: "다른 회원이 함께 본 공고", utm_source: "catch", utm_medium: "related" },
    ],
  },
  {
    id: "jasoseol",
    label: "자소설닷컴",
    faviconDomain: "jasoseol.com",
    children: [
      { id: "ad-044", label: "PC 팝업 배너", utm_source: "jasoseol", utm_medium: "pcpopup" },
      { id: "ad-045", label: "PC 채용공고 배너", utm_source: "jasoseol", utm_medium: "pcrecruit" },
      { id: "ad-046", label: "PC 메인 배너", utm_source: "jasoseol", utm_medium: "pcmain" },
      { id: "ad-047", label: "M 메인 배너", utm_source: "jasoseol", utm_medium: "mmain" },
      { id: "ad-048", label: "M 팝업 배너", utm_source: "jasoseol", utm_medium: "mpopup" },
      { id: "ad-049", label: "M 채팅목록 배너", utm_source: "jasoseol", utm_medium: "mchat" },
      { id: "ad-050", label: "M 텍스트 배너", utm_source: "jasoseol", utm_medium: "mtext" },
      { id: "ad-051", label: "맞춤공고", utm_source: "jasoseol", utm_medium: "fit" },
      { id: "ad-052", label: "앱 푸시 메시지", utm_source: "jasoseol", utm_medium: "push" },
    ],
  },
  {
    id: "careertalk",
    label: "커리어톡",
    faviconDomain: "www.careertalk.kr",
    children: [
      { id: "ad-001", label: "빅배너", utm_source: "careertalk", utm_medium: "big" },
      { id: "ad-002", label: "스페셜배너", utm_source: "careertalk", utm_medium: "special" },
      { id: "ad-003", label: "콘텐츠 단독 배너", utm_source: "careertalk", utm_medium: "contents" },
      { id: "ad-004", label: "카카오 단독 Push", utm_source: "careertalk", utm_medium: "kakaopush" },
      { id: "ad-005", label: "카카오톡 캐러셀 Push 메인", utm_source: "careertalk", utm_medium: "carousel_main" },
      { id: "ad-249", label: "카카오톡 캐러셀 Push 서브", utm_source: "careertalk", utm_medium: "carousel_sub" },
      { id: "ad-006", label: "MMS 타깃 Push", utm_source: "careertalk", utm_medium: "mms" },
      { id: "ad-007", label: "커리어톡TV", utm_source: "careertalk", utm_medium: "tv" },
      { id: "ad-008", label: "페이스북", utm_source: "careertalk", utm_medium: "facebook" },
      { id: "ad-009", label: "인스타그램 피드", utm_source: "careertalk", utm_medium: "insta_feed" },
      { id: "ad-250", label: "인스타그램 스토리", utm_source: "careertalk", utm_medium: "insta_story" },
      { id: "ad-251", label: "포인트", utm_source: "careertalk", utm_medium: "point" },
      { id: "ad-010", label: "링크드인 피드", utm_source: "careertalk", utm_medium: "linkedin" },
    ],
  },
  {
    id: "google",
    label: "구글",
    faviconDomain: "www.google.com",
    children: [
      { id: "ad-075", label: "Google Ads 디스플레이 광고", utm_source: "google", utm_medium: "cpc" },
    ],
  },
  {
    id: "instg",
    label: "인스타그램",
    faviconDomain: "instagram.com",
    children: [
      { id: "ad-071", label: "스토리", utm_source: "instg", utm_medium: "story" },
      { id: "ad-072", label: "피드", utm_source: "instg", utm_medium: "feed" },
    ],
  },
  {
    id: "meta",
    label: "메타",
    faviconDomain: "facebook.com",
    children: [
      { id: "ad-073", label: "스토리", utm_source: "meta", utm_medium: "story" },
      { id: "ad-074", label: "피드", utm_source: "meta", utm_medium: "feed" },
    ],
  },
  {
    id: "linkedin",
    label: "링크드인",
    faviconDomain: "www.linkedin.com",
    children: [
      { id: "ad-176", label: "피드 (단일 이미지)", utm_source: "linkedin", utm_medium: "img" },
      { id: "ad-177", label: "피드 (동영상)", utm_source: "linkedin", utm_medium: "video" },
      { id: "ad-178", label: "피드 (복수 이미지 슬라이드)", utm_source: "linkedin", utm_medium: "carousel" },
      { id: "ad-179", label: "스폰서 InMail", utm_source: "linkedin", utm_medium: "inmail" },
      { id: "ad-180", label: "텍스트 광고", utm_source: "linkedin", utm_medium: "text" },
    ],
  },
  {
    id: "kakao",
    label: "카카오톡",
    faviconDomain: "www.kakaocorp.com",
    children: [
      { id: "ad-042", label: "비즈보드", utm_source: "kakao", utm_medium: "bizboard" },
    ],
  },
  {
    id: "specup",
    label: "스펙업",
    faviconDomain: "cafe.naver.com",
    children: [
      { id: "ad-091", label: "메인 TOP 배너", utm_source: "specup", utm_medium: "maintop" },
      { id: "ad-092", label: "우측 빅배너", utm_source: "specup", utm_medium: "rightbig" },
      { id: "ad-093", label: "우측 띠배너", utm_source: "specup", utm_medium: "rightline" },
      { id: "ad-094", label: "스퀘어 빅배너", utm_source: "specup", utm_medium: "squarebig" },
      { id: "ad-095", label: "글 양식 배너", utm_source: "specup", utm_medium: "article" },
      { id: "ad-096", label: "카카오톡 DM", utm_source: "specup", utm_medium: "kakaodm" },
    ],
  },
  {
    id: "everytime",
    label: "에브리타임",
    faviconDomain: "everytime.kr",
    children: [
      { id: "ad-085", label: "홈배너", utm_source: "everytime", utm_medium: "homebanner" },
      { id: "ad-086", label: "홈카드", utm_source: "everytime", utm_medium: "homecard" },
      { id: "ad-087", label: "채용 정보", utm_source: "everytime", utm_medium: "recruit" },
      { id: "ad-088", label: "커뮤니티 보드", utm_source: "everytime", utm_medium: "board" },
      { id: "ad-089", label: "커뮤니티 네이티브", utm_source: "everytime", utm_medium: "native" },
      { id: "ad-090", label: "데일리 메시지", utm_source: "everytime", utm_medium: "daily" },
    ],
  },
  {
    id: "snulife",
    label: "스누라이프",
    faviconDomain: "www.snulife.com",
    children: [
      { id: "ad-011", label: "PC 메인 A 배너", utm_source: "snulife", utm_medium: "pcmaina" },
      { id: "ad-012", label: "PC 메인 B 배너", utm_source: "snulife", utm_medium: "pcmainb" },
      { id: "ad-013", label: "게시글 배너", utm_source: "snulife", utm_medium: "article" },
      { id: "ad-014", label: "M 게시판 배너", utm_source: "snulife", utm_medium: "mboard" },
    ],
  },
  {
    id: "seiyon",
    label: "세연넷",
    faviconDomain: "www.seiyon.net",
    children: [
      { id: "ad-015", label: "PC 메인 배너", utm_source: "seiyon", utm_medium: "pcmain" },
      { id: "ad-016", label: "M 메인 배너", utm_source: "seiyon", utm_medium: "mmain" },
    ],
  },
  {
    id: "knocks",
    label: "노크",
    faviconDomain: "knocks.co.kr",
    children: [
      { id: "ad-017", label: "PC 메인 배너", utm_source: "knocks", utm_medium: "pcmain" },
      { id: "ad-018", label: "App 메인 배너", utm_source: "knocks", utm_medium: "appmain" },
      { id: "ad-019", label: "게시판 배너", utm_source: "knocks", utm_medium: "board" },
    ],
  },
  {
    id: "koreapas",
    label: "고파스",
    faviconDomain: "www.koreapas.com",
    children: [
      { id: "ad-020", label: "PC 메인 배너", utm_source: "koreapas", utm_medium: "pcmain" },
      { id: "ad-021", label: "M 메인 배너", utm_source: "koreapas", utm_medium: "mmain" },
      { id: "ad-022", label: "PC 게시판 상단 배너", utm_source: "koreapas", utm_medium: "pcboard" },
      { id: "ad-023", label: "인스타 홍보 게시글", utm_source: "koreapas", utm_medium: "instagram" },
      { id: "ad-024", label: "재학생 게시판 상단 배너", utm_source: "koreapas", utm_medium: "board" },
    ],
  },
  {
    id: "kadaejeon",
    label: "카대전",
    faviconDomain: "www.facebook.com",
    children: [
      { id: "ad-025", label: "페이스북 홍보 게시글", utm_source: "kadaejeon", utm_medium: "facebook" },
      { id: "ad-026", label: "페이스북 댓글 배너", utm_source: "kadaejeon", utm_medium: "reply" },
      { id: "ad-027", label: "톡유 게시판 댓글 배너", utm_source: "kadaejeon", utm_medium: "talku" },
    ],
  },
  {
    id: "pogong",
    label: "포공채널",
    faviconDomain: "www.facebook.com",
    children: [
      { id: "ad-028", label: "페이스북 홍보 게시글", utm_source: "pogong", utm_medium: "facebook" },
      { id: "ad-029", label: "POVIS 홍보 게시글", utm_source: "pogong", utm_medium: "povis" },
      { id: "ad-030", label: "카카오톡 메시지", utm_source: "pogong", utm_medium: "kakao" },
    ],
  },
  {
    id: "seodam",
    label: "서담",
    faviconDomain: "www.ssodam.com",
    children: [
      { id: "ad-031", label: "PC 팝업 배너", utm_source: "seodam", utm_medium: "pcpopup" },
      { id: "ad-032", label: "M 팝업 배너", utm_source: "seodam", utm_medium: "mpopup" },
      { id: "ad-033", label: "PC 우측 배너", utm_source: "seodam", utm_medium: "pcright" },
      { id: "ad-034", label: "M 메인", utm_source: "seodam", utm_medium: "mmain" },
      { id: "ad-035", label: "M 게시판", utm_source: "seodam", utm_medium: "mboard" },
      { id: "ad-036", label: "M 게시물", utm_source: "seodam", utm_medium: "mpost" },
    ],
  },
  {
    id: "weehan",
    label: "위한",
    faviconDomain: "www.weehan.com",
    children: [
      { id: "ad-037", label: "PC 중앙 배너", utm_source: "weehan", utm_medium: "pccenter" },
      { id: "ad-038", label: "PC 롤링 배너", utm_source: "weehan", utm_medium: "pcroll" },
      { id: "ad-039", label: "PC 게시판 서브 배너", utm_source: "weehan", utm_medium: "pcboard" },
      { id: "ad-040", label: "M 메인 배너", utm_source: "weehan", utm_medium: "mmain" },
    ],
  },
  {
    id: "ewhaian",
    label: "이화이언",
    faviconDomain: "ewhaian.com",
    children: [
      { id: "ad-041", label: "PC 메인 3-A 좌측 배너", utm_source: "ewhaian", utm_medium: "pcmainleft" },
    ],
  },
  {
    id: "remember",
    label: "리멤버",
    faviconDomain: "career.rememberapp.co.kr",
    children: [
      { id: "ad-158", label: "프리미엄 대표기업", utm_source: "remember", utm_medium: "premium" },
      { id: "ad-159", label: "메인 상단 배너", utm_source: "remember", utm_medium: "maintop" },
      { id: "ad-160", label: "메인 중간 배너", utm_source: "remember", utm_medium: "maincenter" },
      { id: "ad-161", label: "공고 상세 사이드 배너", utm_source: "remember", utm_medium: "detail" },
      { id: "ad-162", label: "타겟 공고", utm_source: "remember", utm_medium: "target" },
    ],
  },
  {
    id: "blind",
    label: "블라인드",
    faviconDomain: "www.teamblind.com",
    children: [
      { id: "ad-163", label: "댓글 배너", utm_source: "blind", utm_medium: "comment" },
      { id: "ad-164", label: "피드 광고", utm_source: "blind", utm_medium: "feed" },
      { id: "ad-165", label: "게시글 하단 띠 배너", utm_source: "blind", utm_medium: "articleline" },
      { id: "ad-166", label: "서베이 광고", utm_source: "blind", utm_medium: "survey" },
      { id: "ad-167", label: "앱 알림 서비스", utm_source: "blind", utm_medium: "alarm" },
      { id: "ad-168", label: "브랜딩 보드", utm_source: "blind", utm_medium: "branding" },
    ],
  },
  {
    id: "jobplanet",
    label: "잡플래닛",
    faviconDomain: "www.jobplanet.co.kr",
    children: [
      { id: "ad-169", label: "팝업 배너 광고", utm_source: "jobplanet", utm_medium: "popup" },
      { id: "ad-170", label: "네이티브 배너 광고", utm_source: "jobplanet", utm_medium: "native" },
      { id: "ad-171", label: "디스플레이 배너 광고", utm_source: "jobplanet", utm_medium: "display" },
      { id: "ad-172", label: "스퀘어 배너 광고", utm_source: "jobplanet", utm_medium: "square" },
    ],
  },
  {
    id: "wanted",
    label: "원티드",
    faviconDomain: "www.wanted.co.kr",
    children: [
      { id: "ad-173", label: "메인 배너", utm_source: "wanted", utm_medium: "main" },
      { id: "ad-174", label: "직무 상단 광고", utm_source: "wanted", utm_medium: "top" },
      { id: "ad-175", label: "회원 대상 이메일", utm_source: "wanted", utm_medium: "email" },
    ],
  },
  {
    id: "naver",
    label: "네이버",
    faviconDomain: "www.naver.com",
    children: [
      { id: "ad-067", label: "브랜드 검색 광고", utm_source: "naver", utm_medium: "brandsearch" },
      { id: "ad-068", label: "치지직 인스트림 15초 SKIP 광고", utm_source: "naver", utm_medium: "instreaml" },
      { id: "ad-069", label: "치지직 인스트림 5초 SKIP 광고", utm_source: "naver", utm_medium: "instreams" },
    ],
  },
  {
    id: "toss",
    label: "토스",
    faviconDomain: "toss.im",
    children: [
      { id: "ad-078", label: "썸네일 배너", utm_source: "toss", utm_medium: "thumbnail" },
      { id: "ad-079", label: "리스트/모먼트 배너", utm_source: "toss", utm_medium: "list" },
      { id: "ad-080", label: "풀페이지 배너", utm_source: "toss", utm_medium: "fullpage" },
      { id: "ad-081", label: "머니 알림", utm_source: "toss", utm_medium: "money" },
      { id: "ad-082", label: "행운 퀴즈", utm_source: "toss", utm_medium: "quiz" },
      { id: "ad-083", label: "이번주 미션", utm_source: "toss", utm_medium: "mission" },
      { id: "ad-084", label: "게시물 보고 포인트 받기", utm_source: "toss", utm_medium: "article" },
    ],
  },
  {
    id: "danggeun",
    label: "당근",
    faviconDomain: "www.daangn.com",
    children: [
      { id: "ad-076", label: "네이티브 피드 광고", utm_source: "danggeun", utm_medium: "feed" },
      { id: "ad-077", label: "검색 광고", utm_source: "danggeun", utm_medium: "search" },
    ],
  },
  {
    id: "linkareer",
    label: "링커리어",
    faviconDomain: "linkareer.com",
    children: [
      { id: "ad-097", label: "메인 배너", utm_source: "linkareer", utm_medium: "main" },
      { id: "ad-098", label: "ALL 커버 배너", utm_source: "linkareer", utm_medium: "allcover" },
      { id: "ad-099", label: "핫라인 배너", utm_source: "linkareer", utm_medium: "hotline" },
      { id: "ad-100", label: "추천활동 배너", utm_source: "linkareer", utm_medium: "recommend" },
      { id: "ad-101", label: "금주의 인기공고 배너", utm_source: "linkareer", utm_medium: "popular" },
      { id: "ad-102", label: "채용 배너", utm_source: "linkareer", utm_medium: "rcrt" },
      { id: "ad-103", label: "커뮤니티 배너", utm_source: "linkareer", utm_medium: "commbanner" },
    ],
  },
  {
    id: "campuspick",
    label: "캠퍼스픽",
    faviconDomain: "www.campuspick.com",
    children: [
      { id: "ad-104", label: "커뮤니티 보드", utm_source: "campuspick", utm_medium: "commboard" },
      { id: "ad-105", label: "활동 배너", utm_source: "campuspick", utm_medium: "actbanner" },
    ],
  },
  {
    id: "ssgsag",
    label: "슥삭",
    faviconDomain: "www.ssgsag.kr",
    children: [
      { id: "ad-106", label: "1순위 타겟팅", utm_source: "ssgsag", utm_medium: "firsttg" },
      { id: "ad-107", label: "오픈팝업", utm_source: "ssgsag", utm_medium: "popup" },
      { id: "ad-108", label: "인기배너", utm_source: "ssgsag", utm_medium: "popular" },
      { id: "ad-109", label: "최상단배너", utm_source: "ssgsag", utm_medium: "top" },
      { id: "ad-110", label: "카테고리 상단배너", utm_source: "ssgsag", utm_medium: "category" },
    ],
  },
  {
    id: "outcampus",
    label: "아웃캠퍼스",
    faviconDomain: "cafe.naver.com",
    children: [
      { id: "ad-111", label: "카페 상단 배너", utm_source: "outcampus", utm_medium: "top" },
      { id: "ad-112", label: "카페 상단 우측 배너", utm_source: "outcampus", utm_medium: "topright" },
      { id: "ad-113", label: "카페 메인&서브 배너", utm_source: "outcampus", utm_medium: "mainsub" },
      { id: "ad-114", label: "카페 추천 배너", utm_source: "outcampus", utm_medium: "recommend" },
      { id: "ad-115", label: "유튜브 1분합격자기소개", utm_source: "outcampus", utm_medium: "selfintro" },
      { id: "ad-116", label: "유튜브 합격인사이트", utm_source: "outcampus", utm_medium: "insight" },
      { id: "ad-117", label: "인스타그램 추천리스트 3p", utm_source: "outcampus", utm_medium: "threep" },
      { id: "ad-118", label: "인스타그램 금주의 아캠 pick", utm_source: "outcampus", utm_medium: "weekpick" },
      { id: "ad-119", label: "페이스북 단독 포스팅", utm_source: "outcampus", utm_medium: "facebook" },
    ],
  },
  {
    id: "allforyoung",
    label: "요즘것들",
    faviconDomain: "www.allforyoung.com",
    children: [
      { id: "ad-120", label: "페이스북 최상단 배너", utm_source: "allforyoung", utm_medium: "top" },
      { id: "ad-121", label: "페이스북 띠배너", utm_source: "allforyoung", utm_medium: "line" },
      { id: "ad-122", label: "페이스북 랭킹배너", utm_source: "allforyoung", utm_medium: "rank" },
      { id: "ad-123", label: "페이스북 픽배너", utm_source: "allforyoung", utm_medium: "pick" },
      { id: "ad-124", label: "페이스북 와이드배너", utm_source: "allforyoung", utm_medium: "wide" },
    ],
  },
  {
    id: "detizen",
    label: "대티즌",
    faviconDomain: "www.detizen.com",
    children: [
      { id: "ad-125", label: "TOP 배너", utm_source: "detizen", utm_medium: "top" },
      { id: "ad-126", label: "스페셜 A 배너", utm_source: "detizen", utm_medium: "speciala" },
      { id: "ad-127", label: "스페셜 B 배너", utm_source: "detizen", utm_medium: "specialb" },
      { id: "ad-128", label: "BAND 배너", utm_source: "detizen", utm_medium: "band" },
      { id: "ad-129", label: "CHOICE 배너", utm_source: "detizen", utm_medium: "choice" },
      { id: "ad-130", label: "LOGIN 배너", utm_source: "detizen", utm_medium: "login" },
      { id: "ad-131", label: "SNS 카드 뉴스", utm_source: "detizen", utm_medium: "snscard" },
      { id: "ad-132", label: "단독 EDM", utm_source: "detizen", utm_medium: "edm" },
    ],
  },
  {
    id: "allcon",
    label: "올콘",
    faviconDomain: "www.all-con.co.kr",
    children: [
      { id: "ad-133", label: "메인 A 배너", utm_source: "allcon", utm_medium: "maina" },
      { id: "ad-134", label: "메인 B 배너", utm_source: "allcon", utm_medium: "mainb" },
      { id: "ad-135", label: "메인 C / 이벤트 배너", utm_source: "allcon", utm_medium: "mainc" },
      { id: "ad-136", label: "롤링 D 배너", utm_source: "allcon", utm_medium: "rollingd" },
      { id: "ad-137", label: "게시판 상위 고정", utm_source: "allcon", utm_medium: "articletop" },
    ],
  },
  {
    id: "thinkcon",
    label: "씽굿",
    faviconDomain: "www.thinkcontest.com",
    children: [
      { id: "ad-138", label: "A배너", utm_source: "thinkcon", utm_medium: "abanner" },
      { id: "ad-139", label: "B배너", utm_source: "thinkcon", utm_medium: "bbanner" },
      { id: "ad-140", label: "C배너", utm_source: "thinkcon", utm_medium: "cbanner" },
      { id: "ad-141", label: "D배너", utm_source: "thinkcon", utm_medium: "dbanner" },
      { id: "ad-142", label: "S1배너", utm_source: "thinkcon", utm_medium: "s1" },
      { id: "ad-143", label: "S2배너", utm_source: "thinkcon", utm_medium: "s2" },
      { id: "ad-144", label: "로그인배너", utm_source: "thinkcon", utm_medium: "login" },
      { id: "ad-145", label: "M1배너", utm_source: "thinkcon", utm_medium: "m1" },
      { id: "ad-146", label: "M2배너", utm_source: "thinkcon", utm_medium: "m2" },
    ],
  },
  {
    id: "wevity",
    label: "위비티",
    faviconDomain: "www.wevity.com",
    children: [
      { id: "ad-147", label: "팝업배너", utm_source: "wevity", utm_medium: "popup" },
      { id: "ad-148", label: "모바일 상단 배너", utm_source: "wevity", utm_medium: "mobiletop" },
      { id: "ad-149", label: "웹 상단 배너", utm_source: "wevity", utm_medium: "webtop" },
      { id: "ad-150", label: "웹 메인 우측 배너", utm_source: "wevity", utm_medium: "webmainright" },
      { id: "ad-151", label: "웹 스페셜 배너", utm_source: "wevity", utm_medium: "webspecial" },
    ],
  },
  {
    id: "boottent",
    label: "부트텐트",
    faviconDomain: "boottent.com",
    children: [
      { id: "ad-152", label: "메인배너", utm_source: "boottent", utm_medium: "main" },
      { id: "ad-153", label: "상위노출카드", utm_source: "boottent", utm_medium: "top" },
      { id: "ad-154", label: "이벤트 적용", utm_source: "boottent", utm_medium: "event" },
      { id: "ad-155", label: "디데이 적용", utm_source: "boottent", utm_medium: "dday" },
      { id: "ad-156", label: "타이틀 태그", utm_source: "boottent", utm_medium: "title" },
    ],
  },
  {
    id: "letspl",
    label: "렛플",
    faviconDomain: "letspl.me",
    children: [
      { id: "ad-157", label: "확인 필요", utm_source: "letspl", utm_medium: "" },
    ],
  },
  {
    id: "programmers",
    label: "프로그래머스",
    faviconDomain: "programmers.co.kr",
    children: [
      { id: "ad-181", label: "메인 배너", utm_source: "programmers", utm_medium: "main" },
    ],
  },
  {
    id: "okky",
    label: "OKKY",
    faviconDomain: "okky.kr",
    children: [
      { id: "ad-182", label: "메인 페이지 상단 중앙", utm_source: "okky", utm_medium: "maincenter" },
      { id: "ad-183", label: "메인 페이지 스크롤 다운 우측", utm_source: "okky", utm_medium: "mainright" },
      { id: "ad-184", label: "메인 페이지 스크롤 다운 좌측", utm_source: "okky", utm_medium: "mainleft" },
      { id: "ad-185", label: "목록 페이지 배너", utm_source: "okky", utm_medium: "list" },
      { id: "ad-186", label: "상세 페이지 배너", utm_source: "okky", utm_medium: "detail" },
      { id: "ad-187", label: "온라인 eDM 광고", utm_source: "okky", utm_medium: "edm" },
      { id: "ad-188", label: "Page in 광고", utm_source: "okky", utm_medium: "pagein" },
    ],
  },
  {
    id: "gamejob",
    label: "게임잡",
    faviconDomain: "www.gamejob.co.kr",
    children: [
      { id: "ad-189", label: "백스킨 배너", utm_source: "gamejob", utm_medium: "backskin" },
      { id: "ad-190", label: "메인 탑 배너", utm_source: "gamejob", utm_medium: "maintop" },
      { id: "ad-191", label: "메인 상단띠", utm_source: "gamejob", utm_medium: "maintopline" },
      { id: "ad-192", label: "메인 미들띠", utm_source: "gamejob", utm_medium: "mainmiddleline" },
      { id: "ad-193", label: "서브스카이", utm_source: "gamejob", utm_medium: "subsky" },
      { id: "ad-194", label: "서브하단", utm_source: "gamejob", utm_medium: "subbottom" },
      { id: "ad-195", label: "모바일 메인띠", utm_source: "gamejob", utm_medium: "mobilemain" },
      { id: "ad-252", label: "엠페러", utm_source: "gamejob", utm_medium: "emperor" },
    ],
  },
  {
    id: "baekjoon",
    label: "백준",
    faviconDomain: "www.acmicpc.net",
    children: [
      { id: "ad-196", label: "메인 페이지 광고", utm_source: "baekjoon", utm_medium: "main" },
      { id: "ad-197", label: "채점 현황 페이지 상단 배너", utm_source: "baekjoon", utm_medium: "evaluate" },
    ],
  },
  {
    id: "hibrain",
    label: "하이브레인넷",
    faviconDomain: "www.hibrain.net",
    children: [
      { id: "ad-198", label: "플래티넘 플러스 배너", utm_source: "hibrain", utm_medium: "platinumplus" },
      { id: "ad-199", label: "플래티넘 배너", utm_source: "hibrain", utm_medium: "platinum" },
      { id: "ad-200", label: "골드 배너", utm_source: "hibrain", utm_medium: "gold" },
      { id: "ad-201", label: "실버 배너", utm_source: "hibrain", utm_medium: "silver" },
      { id: "ad-202", label: "브론즈 배너", utm_source: "hibrain", utm_medium: "bronze" },
      { id: "ad-203", label: "줄광고", utm_source: "hibrain", utm_medium: "line" },
    ],
  },
  {
    id: "phdkim",
    label: "김박사넷",
    faviconDomain: "phdkim.net",
    children: [
      { id: "ad-204", label: "메인 배너 (프리미엄)", utm_source: "phdkim", utm_medium: "mainpremium" },
      { id: "ad-205", label: "메인 배너 (베이직)", utm_source: "phdkim", utm_medium: "mainbasic" },
      { id: "ad-206", label: "팝업 광고", utm_source: "phdkim", utm_medium: "popup" },
      { id: "ad-207", label: "최상단 띠배너", utm_source: "phdkim", utm_medium: "top" },
      { id: "ad-208", label: "중단 띠배너", utm_source: "phdkim", utm_medium: "middle" },
      { id: "ad-209", label: "캐러셀 광고", utm_source: "phdkim", utm_medium: "carousel" },
    ],
  },
  {
    id: "bagstrap",
    label: "가방끈",
    faviconDomain: "www.bagstrap.team",
    children: [
      { id: "ad-210", label: "메인 상단배너", utm_source: "bagstrap", utm_medium: "maintop" },
      { id: "ad-211", label: "하단 가로형 배너", utm_source: "bagstrap", utm_medium: "bottom" },
      { id: "ad-212", label: "채용공고", utm_source: "bagstrap", utm_medium: "recruit" },
      { id: "ad-213", label: "커뮤니티 게시글 광고", utm_source: "bagstrap", utm_medium: "article" },
      { id: "ad-214", label: "앱 푸시 메세지", utm_source: "bagstrap", utm_medium: "push" },
    ],
  },
  {
    id: "peoplenjob",
    label: "피플앤잡",
    faviconDomain: "www.peoplenjob.com",
    children: [
      { id: "ad-215", label: "G-1 배너 상품", utm_source: "peoplenjob", utm_medium: "g1" },
      { id: "ad-216", label: "G-2 배너 상품", utm_source: "peoplenjob", utm_medium: "g2" },
      { id: "ad-217", label: "M 그랜드 배너 상품", utm_source: "peoplenjob", utm_medium: "mgrand" },
      { id: "ad-218", label: "R 그랜드 배너 상품", utm_source: "peoplenjob", utm_medium: "rgrand" },
    ],
  },
  {
    id: "superookie",
    label: "슈퍼루키",
    faviconDomain: "www.superookie.com",
    children: [
      { id: "ad-219", label: "메인 빅배너", utm_source: "superookie", utm_medium: "mainbig" },
      { id: "ad-220", label: "메인 상단 배너", utm_source: "superookie", utm_medium: "mtop" },
      { id: "ad-221", label: "채용 공고 상단 배너", utm_source: "superookie", utm_medium: "article" },
      { id: "ad-222", label: "사이드 배너", utm_source: "superookie", utm_medium: "side" },
      { id: "ad-223", label: "메인 체크리스트", utm_source: "superookie", utm_medium: "maincheck" },
      { id: "ad-224", label: "채용공고 사이드 배너", utm_source: "superookie", utm_medium: "recruitside" },
      { id: "ad-225", label: "추천 채용 공고 배너", utm_source: "superookie", utm_medium: "recommend" },
      { id: "ad-226", label: "채용공고 최상단 고정 옵션", utm_source: "superookie", utm_medium: "articletop" },
    ],
  },
  {
    id: "dmand",
    label: "디맨드",
    faviconDomain: "www.dmand.co.kr",
    children: [
      { id: "ad-227", label: "시작 팝업 모달", utm_source: "dmand", utm_medium: "startpopupmodal" },
      { id: "ad-228", label: "홈 하이라이트 배너", utm_source: "dmand", utm_medium: "homehilight" },
      { id: "ad-229", label: "홈 포커스 배너", utm_source: "dmand", utm_medium: "homefocus" },
      { id: "ad-230", label: "디맨드 추천 공고", utm_source: "dmand", utm_medium: "recommend" },
      { id: "ad-231", label: "홈 라인 배너", utm_source: "dmand", utm_medium: "homeline" },
      { id: "ad-232", label: "오늘 HOT한 공고", utm_source: "dmand", utm_medium: "hot" },
      { id: "ad-233", label: "채용 프리미엄 배너", utm_source: "dmand", utm_medium: "premium" },
      { id: "ad-234", label: "지금 주목받는 공고", utm_source: "dmand", utm_medium: "pop" },
    ],
  },
  {
    id: "albamon",
    label: "알바몬",
    faviconDomain: "www.albamon.com",
    children: [
      { id: "ad-235", label: "M 지역 TOP 배너", utm_source: "albamon", utm_medium: "mtop" },
      { id: "ad-236", label: "플래티넘 VIP 배너", utm_source: "albamon", utm_medium: "platinumvip" },
      { id: "ad-237", label: "그랜드 배너", utm_source: "albamon", utm_medium: "grand" },
      { id: "ad-238", label: "M 지역 그랜드", utm_source: "albamon", utm_medium: "mgrand" },
    ],
  },
  {
    id: "worker",
    label: "건설워커",
    faviconDomain: "www.worker.co.kr",
    children: [
      { id: "ad-239", label: "VIP 배너형 채용속보", utm_source: "worker", utm_medium: "vipbanner" },
      { id: "ad-240", label: "GRAND 배너형 플러스 채용속보", utm_source: "worker", utm_medium: "grand" },
      { id: "ad-241", label: "건설워커 빅배너 광고", utm_source: "worker", utm_medium: "bigbanner" },
    ],
  },
  {
    id: "notefolio",
    label: "노트폴리오",
    faviconDomain: "notefolio.net",
    children: [
      { id: "ad-242", label: "상단 띠 배너 광고", utm_source: "notefolio", utm_medium: "topline" },
      { id: "ad-243", label: "메인 롤링 광고", utm_source: "notefolio", utm_medium: "mainrolling" },
      { id: "ad-244", label: "콘텐츠형 디스플레이 광고", utm_source: "notefolio", utm_medium: "contents" },
      { id: "ad-245", label: "메인 팝업 배너 광고", utm_source: "notefolio", utm_medium: "mpopup" },
      { id: "ad-246", label: "인스타그램 포스팅", utm_source: "notefolio", utm_medium: "instagram" },
    ],
  },
  {
    id: "loud",
    label: "라우드소싱",
    faviconDomain: "www.loud.kr",
    children: [
      { id: "ad-247", label: "eDM 발송", utm_source: "loud", utm_medium: "edm" },
    ],
  },
  {
    id: "inthiswork",
    label: "인디스워크",
    faviconDomain: "inthiswork.com",
    children: [
      { id: "ad-248", label: "채용공고", utm_source: "inthiswork", utm_medium: "article" },
    ],
  },
] as const;
